version: "3.9"

services:
  flask:
    build: .
    container_name: riiqimaker
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5100:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./static:/app/static
    networks:
      - default
      - supabase_default

networks:
  supabase_default:
    external: true
